[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "ez_pipeline"
version = "0.0.1"
description = "Library for constructing data processing pipelines using the pipe '|' operator"
authors = ["Nick Burnett <PVjammer@gmail.com>"]

